# Generated by Django 5.1.2 on 2024-12-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("efficiency_score", models.FloatField(blank=True, null=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
