# Generated by Django 5.1.2 on 2024-12-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks_api", "0004_alter_task_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("efficiency_score", models.FloatField(blank=True, null=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="tasks_api.task",
                    ),
                ),
            ],
        ),
    ]
