# Generated by Django 5.1.2 on 2024-12-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports_api", "0001_initial"),
        ("tasks_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskreport",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report",
                to="tasks_api.task",
            ),
        ),
    ]
