# Generated by Django 5.1.2 on 2024-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskreport",
            name="efficiency_score",
            field=models.FloatField(),
        ),
    ]
