# Generated by Django 5.1.2 on 2024-12-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_api", "0002_taskreport_time_create"),
        ("tasks_api", "0004_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskreport",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report",
                to="tasks_api.task",
            ),
        ),
    ]
