# Generated by Django 5.1.2 on 2024-12-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports_api", "0003_alter_taskreport_efficiency_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskreport",
            options={"ordering": ["-time_create"]},
        ),
    ]
