# Generated by Django 5.1.2 on 2024-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_api", "0004_alter_taskreport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskreport",
            name="is_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
