# Generated by Django 5.1.2 on 2024-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_managercode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
