# Generated by Django 5.1.2 on 2024-12-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("task_duration", models.DurationField(blank=True, null=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_completion", models.DateTimeField(blank=True, null=True)),
                ("time_start", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
