# Generated by Django 5.1.2 on 2024-12-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="time_spent",
        ),
        migrations.AddField(
            model_name="task",
            name="time_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
