# Generated by Django 5.1.2 on 2024-12-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_duration",
            field=models.DurationField(),
        ),
    ]
