# Generated by Django 5.1.2 on 2024-12-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_api", "0003_task_task_creator_alter_task_task_performer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
