# Generated by Django 5.1.2 on 2024-12-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_api", "0003_alter_task_task_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-time_create"]},
        ),
    ]
