# Generated by Django 5.1.2 on 2024-12-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reward_sum", models.DecimalField(decimal_places=2, max_digits=7)),
                ("comment", models.TextField()),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                (
                    "task_report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward",
                        to="reports_api.taskreport",
                    ),
                ),
            ],
        ),
    ]
