# Generated by Django 5.1.2 on 2024-12-18 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards_api", "0002_alter_reward_reward_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
